
title: "Josh Dick"
tagline: ""
description: "Follow <a href=\"https://micro.blog/jd\">@jd on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/jd\">@jd on Micro.blog</a>."
baseurl: ""
url: "https://jd.micro.blog"
markdown: "kramdown"
username: "jd"
microblog_user: "jd"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Josh Dick"
name: "Josh Dick"
gravatar_hash: "0b774135511c0c91cf81be7b4cdee7e6"
avatar: "https://micro.blog/jd/avatar.jpg"
full_name: "Josh Dick"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Michigan"
site_id: "462"
gems: ["jekyll-paginate"]
itunes_description: "Puckish coffee addict. Programmer. Drummer. Fourth thing. ⌨☕"
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Josh Dick"
itunes_email: ""
podcast: false